services:
  # Database services
  postgres:
    image: postgres:14
    container_name: postgres
    network_mode: host
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lyn
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    network_mode: host
    volumes:
      - qdrant_data:/qdrant/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Application services
  database:
    build:
      context: .
      dockerfile: services/database/Dockerfile
      args:
        - BUILD_ENV=${BUILD_ENV:-development}
    network_mode: host
    environment:
      - RUST_LOG=info
      - DATABASE_URL=postgres://postgres:postgres@localhost:5432/lyn
      - DB_PORT=8081
      - SERVER_HOST=0.0.0.0
    depends_on:
      - postgres

  proxy-service:
    build:
      context: .
      dockerfile: services/proxy-service/Dockerfile
      args:
        - BUILD_ENV=${BUILD_ENV:-development}
    network_mode: host
    volumes:
      - llama_models:/models
    environment:
      - RUST_LOG=info
      - API_PORT=8083
      - SERVER_HOST=0.0.0.0
      - LYN_PROVIDER_CONFIGS_LLAMACPP_URL=http://localhost
      - LYN_PROVIDER_CONFIGS_LLAMACPP_PORT=8084
      - LLAMA_ARG_MODEL=/models/gemma-3-1b-it-Q8_0.gguf
    hostname: proxy-service

  embeddings:
    build:
      context: .
      dockerfile: services/embeddings/Dockerfile
      args:
        - BUILD_ENV=${BUILD_ENV:-development}
    network_mode: host
    environment:
      - RUST_LOG=info
      - QDRANT_URL=http://localhost:6333
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8082
      - LYN_EMBEDDING_PROVIDER_CONFIGS_OLLAMA_URL=http://localhost
      - LYN_EMBEDDING_PROVIDER_CONFIGS_OLLAMA_PORT=8084
    depends_on:
      - qdrant

  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - ./ui:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8080
      - VITE_WS_BASE_URL=ws://localhost:8083
      - VITE_LLM_PROXY_URL=http://localhost:8083
      - NODE_ENV=development
    command: npm run dev -- --host
    depends_on:
      - embeddings
      - proxy-service

volumes:
  postgres_data:
  qdrant_data:
  llama_models:
